apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: CLUSTER_NAME
  name: test-node
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210415
  machineType: t3.medium
  maxSize: 4
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: test-node
    node: test-node
  role: Node
  subnets:
  - us-east-1a